### ISSUE TITLE
Datacite format returns the record._id in the identifier field instead of record.doi

### ISSUE THREAD

**Issue by minottic** [SciCatProject/oai-provider-service#80]
https://github.com/SciCatProject/oai-provider-service/blob/master/src/providers/scicat-provider/repository/openaire-mapper.ts#L63-L65

differs from
https://github.com/SciCatProject/oai-provider-service/blob/master/src/providers/scicat-provider/repository/scicat-dc-mapper.ts#L55

while they should contain the same information.

change openaier mapper to use record.doi

**Comment by minottic** [comment]
@henrikjohansson712 I see you have some custom CI files which update what to show in the identifier filed. 
Do you see any problem if I do what described in the issue (let me know if unclear)
Thanks!

**Comment by henrikjohansson712** [comment]
No problem, Carlo, go ahead! We don't use this repo

**Comment by minottic** [comment]
ok, thanks! If you are not using it, how do you achieve this: http://b2find.eudat.eu/dataset/8e9eac39-5dfc-576c-891f-52b04eb4da96 e.g.? Just to understand if I can use your approach as well.
Thanks!

**Comment by henrikjohansson712** [comment]
We're using the PaNOSC one: https://github.com/panosc-eu/harvest-api

**Comment by minottic** [comment]
ah thanks, I didn't even know it existed. Having a look!

**Comment by henrikjohansson712** [comment]
It should be pretty much the same but without the unauthenticated endpoints for updating Publsihed Data

**Comment by minottic** [comment]
is this repo maintained then or do we plan to dismiss it since there is the other one?

**Comment by henrikjohansson712** [comment]
The PaNOSC one isn't maintained at all, this repo I've set up to use Snyk for automatic updates. I'd prefer to use this one, but for that we first need to do something to disable the Published Data endpoints on our end.

**Comment by minottic** [comment]
understood, thank you. Then I think PSI will stay with this one. What I was thinking to do, about the unauthenticated endpoints for updating Publsihed Data, as we don't need them anymore, is to do some path-based routing in the reverse proxy (a k8s ingress in our case), so that those ones are not reachable. Maybe this solution could work in your case as well.

**Comment by minottic** [comment]
closed by #85
